name: PrisonRankup
version: 3.1
main: io.mazenmc.prisonrankup.PrisonRankupPlugin
commands:
  rankup:
    description: Rankup
    aliases: [rnkup, erankup, rankup]
    permission: prisonrankup.rankup
  ranks:
    description: Displays available ranks
    aliases: [rnks, eranks, ernks]
    permission: prisonrankup.ranks
